---
    - name: "install apache server"
      yum:
        name: httpd
        state: latest
    - name: "install php"
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
         - php
         - php-mysql
         - MySQL-python