---
- name: "download wordpress"
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
- name: "Unarchive wordpress "
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www
    remote_src: yes